FROM openjdk:16-jdk-alpine

RUN apk add --no-cache --upgrade bash

COPY shared_volume/cosdodevopsa-1.0-SNAPSHOT.jar /cosdodevopsa-1.0-SNAPSHOT.jar

ENTRYPOINT [ "java", "-jar", "cosdodevopsa-1.0-SNAPSHOT.jar" ]
